t1 = (1, 2, 3, 4, 5)
t2 = tuple(i for i in range(6, 11))
print(t1, t2)
print(tuple(map(int.__mul__, t1, t2)))
print(tuple(map(int.__add__, t1, t2)))
print(tuple(map(int.__sub__, t1, t2)))
print(tuple(map(int.__sub__, t2, t1)))
print(tuple(map(int.__divmod__(), t1, t2)))
print(tuple(map(int.__truediv__, t1, t2)))
print(tuple(map(int.__floordiv__, t1, t2)))
print(tuple(map(int.__floordiv__, t2, t1)))
